apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm
data:
  app.properties: |
    server.port= 9000
    server.servlet.context-path=/oracle 
    oracleprops.greeting= Thank you and visit again - altered 
    oracleprops.greeting1= New Data
  db_hostname: "oraclehost"
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
spec:
  volumes:
    - name: cm-vol
      configMap: 
        name: app-cm
  containers:
    - name: cm-pod
      image: redis
      volumeMounts: 
        - name: cm-vol
          mountPath: /etc/configmap

      env:
        - name: db_hostname
          valueFrom:
            configMapKeyRef:
              name: app-cm
              key: db_hostname
        - name: appproperties
          valueFrom:
            configMapKeyRef:
              name: app-cm
              key: app.properties

---
apiVersion: v1 
data:
  stub.server: |
    company.com {
      errors
      cache 30
      forward . 10.0.0.1 10.0.0.2 192.0.0.10
    }  
kind: ConfigMap ## to route traffic to internal dns servers
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {}
  name: coredns-custom
  namespace: kube-system ##
