podLevelTroubleshooting: |
      k describe pod web ## pods/nodes/deployments # 
      k logs web -f --previous ## previous pod  
      k edit pod <pod-name>
      k get pods -Lapp -Ltier ## -L = --label-columns ; k get pods -l app=nginx
      kubectl exec <POD-NAME> -c <CONTAINER-NAME> -- <COMMAND>

      kubectl logs ${POD_NAME} ${CONTAINER_NAME}
      kubectl logs --previous ${POD_NAME} ${CONTAINER_NAME} ## previous container crash log..

IMP: networking commands(like nslookup) can run on BUSYBOX container

Note: if deployments not scheduling pods, check pods status in kube-system ns and describe them if any crashLoopBackOff. 

Toedit:
    k get pods test-pod -oyaml > test-copy.yaml ; k delete pod test-pod ; k create -f test-copy.yaml # after edit. 
    Can't edit pod for all-situations. Ex=To add securityContext, need to delete and recreate pod. 
---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    app: tomcat
    tier: dev

spec:
  containers:
    - image: vishymails/tomcatimage:1.0
      name: tomcat-container