volumeTypes:
    emptyDir: works as cache, if pod object deleted and recreated, it will not retain the data under volume. 
    hostPath: creates on a node. Can be retained after pod deletion, but only on particular node where pod got created. 
    PersistentVolume: |
          default=> accessModes:RWO/RWM, storageClassName:slow/fast/manual
          pv: capacity.storage: 10Gi, hostpath/nfs, 
          pvc: resources.requests.storage: 5Gi 
          pod: spec.volumes[].persistentVolumeClaim = pvc

Note: pvc auto-bounds to pv on matched storage class + storage # manualbound=.spec.volumeName

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  nfs:
    path: /tmp
    server: 172.17.0.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv2
  labels:
    type: local
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: manual
  capacity: 
    storage: 2Gi
  hostPath:
    path: /mnt/datas
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec: 
  storageClassName: manual
  resources:
    requests: 
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: test-pod
spec:
  volumes:
    - name: test-pvc-vol
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
        - name: test-pvc-vol
          mountPath: /test-pv
      ports:
        - containerPort: 80
