
### default: accessModes, storageClassName 
### pv: capacity.storage, hostpath/nfs, 
### pvc: resources.requests.storage
### pod: spec.volumes[].persistentVolumeClaim = pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  nfs:
    path: /tmp
    server: 172.17.0.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv2
  labels:
    type: local
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: manual
  capacity: 
    storage: 2Gi
  hostPath:
    path: /mnt/datas
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec: 
  storageClassName: manual
  resources:
    requests: 
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: test-pod
spec:
  volumes:
    - name: test-pvc-vol
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
        - name: test-pvc-vol
          mountPath: /test-pv
      ports:
        - containerPort: 80
