
CommandWay: | 
      k create rs web-pod --image nginx:1.16 --replicas=3 
      rs.yaml == spec.selector.matchLabels(app=web) - this will consider if any existing pods with same label while replic-create. 

---
apiVersion: apps/v1
kind: ReplicaSet ## Same manifest works for ReplicationController also
metadata:
  name: tomcat-rs

spec: ## replicas, selector, pod template
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels: ## Replication controller supports only equality-based labels
      app: tomcat-pod
    matchExpressions: ## only for ReplicaSet, RC can't support
      - {key: tier, operator: In, values: [frontend,backend]}
  template:
    metadata:
      labels:
        app: tomcat-pod
        tier: frontend
    spec:
      containers:
        - image: vishymails/tomcatimage:1.0
          name: tomcat-container
          ports:
            - containerPort: 8080


