apiVersion: v1
kind: Secret ## k create secret generic db-user-pass --from-file=./user --from-file=./pass ## --from-literal
metadata:
  name: db-user-pass
data:
  pass: cGFzc0AxMjM=
  user: YWRtaW4=
---
apiVersion: v1
kind: Pod
metadata:
  name: secre-pod
spec:
  volumes: ## 1-way: get the secrets on volume mounts
    - name: secre-vol
      secret: 
        secretName: db-user-pass
  containers:
    - name: secre-pod
      image: redis
      volumeMounts: 
        - name: secre-vol
          mountPath: /etc/secret ## user/pass files gets in here
          
      env:  ## 2-way: get the secrets exported as env vars
        - name: user 
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: user
        - name: pass
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: pass 
