apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: admin-pod
  name: admin-pod
spec:
  containers:
  - command:
    - sleep
    - "3200"
    image: busybox
    name: admin-pod
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
## security Context gives capabilities to the pods to manage host(k8s worker) resources. 

