ServiceTypes: | 
    NodePort --> nodeIP{1,2,3}: nodeport
    LoadBalancer --> IP from nginx-controller: service-port ## get ip <== k get svc -owide(named as CLUSTER IP)
    ClusterIP ->  needed where multiple clusters used (limit:5000nodes/cluster) -Ex: flipkart,amazon - can't use in our usual environments. 

CommandWay: |
      k run my-pod --image= && k get pods
      k expose --help # Jump to examples. 
      k expose pod my-pod --port=80 --name=my-service --type=NodePort $drs
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: tomcat-app
spec:
  selector: 
    app: tomcat-app
  type: NodePort ## same exact manifest for LoadBalancer
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 8080

