apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data
    server: myserver
    readonly: false
